name: "Update Docker Compose Version in versions/docker-compose.yaml"

scms:
  default:
    kind: github
    spec:
      user: "Dubeysatvik123"
      email: "satvikdubey268@gmail.com"
      owner: "Dubeysatvik123"
      repository: "updatecli"
      token: "{{ requiredEnv `GITHUB_TOKEN` }}"
      branch: main

sources:
  dockerComposeVersion:
    kind: shell
    name: Get installed Docker Compose version
    spec:
      command: |
        docker compose version --short 2>/dev/null || docker-compose version --short

conditions: {}

targets:
  updateDockerComposeVersion:
    name: Update Docker Compose version in versions/docker-compose.yaml
    kind: yaml
    sourceid: dockerComposeVersion
    scmid: default
    spec:
      file: versions/docker-compose.yaml
      key: $.docker_compose.version

actions:
  githubPR:
    kind: github/pullrequest
    scmid: default
    title: "chore: update docker-compose version to {{ source `dockerComposeVersion` }}"
    spec:
      automerge: false
      mergemethod: squash
      labels:
        - dependencies
        - automated
      description: |
        ## Docker Compose Version Update
        
        This PR updates the tracked Docker Compose version.
        
        **New Version**: `{{ source "dockerComposeVersion" }}`
        
        ### Changes
        - Updated `versions/docker-compose.yaml`
        
        ### Automation
        - Generated by [Updatecli](https://www.updatecli.io/)
        - Triggered by: Scheduled workflow
        
        ---
        
        Please review and merge if the version is correct.
